version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ltprods-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Valery2005*
      MYSQL_DATABASE: ltprods
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - producto-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  producto-service:
    build: .
    container_name: producto-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ltprods?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Valery2005*
      APP_SECURITY_API_KEY: producto-service-key-2024
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - producto-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  producto-network:
    driver: bridge